export const SLOTS = [
  { id: 'wakeup',  label: 'Wake-up',     time: '6:30 am', emoji: '🌅', target: { p: [3,7],   f: [1,3],  c: [2,6],   k: [80,130]  } },
  { id: 'bfast',   label: 'Breakfast',   time: '8:00 am', emoji: '🥣', target: { p: [12,20], f: [4,9],  c: [30,50], k: [280,350] } },
  { id: 'midmorn', label: 'Mid-morning', time: '11:00 am',emoji: '🥛', target: { p: [8,14],  f: [2,5],  c: [10,28], k: [120,200] } },
  { id: 'lunch',   label: 'Lunch',       time: '1:30 pm', emoji: '🍱', target: { p: [13,20], f: [5,10], c: [42,58], k: [380,470] } },
  { id: 'snack',   label: 'Snack',       time: '4:30 pm', emoji: '🫘', target: { p: [4,12],  f: [2,6],  c: [8,25],  k: [60,185]  } },
  { id: 'dinner',  label: 'Dinner',      time: '7:30 pm', emoji: '🍽️', target: { p: [11,22], f: [3,6],  c: [18,36], k: [280,400] } },
];

export const TAG_META = {
  cooling:  { label: 'cooling',  color: 'bg-blue-50 text-blue-700' },
  summer:   { label: 'summer',   color: 'bg-sky-50 text-sky-700' },
  fibre:    { label: 'high fibre', color: 'bg-green-50 text-green-700' },
  quick:    { label: 'quick',    color: 'bg-gray-100 text-gray-600' },
  oats:     { label: 'oats',     color: 'bg-amber-50 text-amber-700' },
  sattu:    { label: 'sattu',    color: 'bg-teal-50 text-teal-700' },
  soya:     { label: 'soya',     color: 'bg-violet-50 text-violet-700' },
  paneer:   { label: 'paneer',   color: 'bg-pink-50 text-pink-700' },
  chaas:    { label: 'chaas',    color: 'bg-sky-50 text-sky-700' },
  chana:    { label: 'chana',    color: 'bg-amber-50 text-amber-700' },
  flexi:    { label: 'flexi',    color: 'bg-rose-50 text-rose-600' },
};

export const CONSTRAINTS = [
  'Soya chunks max 4×/week — never on 2 consecutive days',
  'Paneer max 2×/week — low-fat only, no cream ever',
  '4:30 pm snack alternates — chaas one day, chana chaat the next',
  'Always eat kachumber salad before lunch',
  '1 tbsp ground flaxseed in atta every day',
  'Dinner done by 8 pm · 3–3.5 litres water daily (summer)',
  'No bajra roti until October · Dal makhani only Oct–Feb',
];

export const OPTIONS = {
  wakeup: [
    { name: 'Warm water + soaked almonds (8) + walnuts (4)', detail: 'Soak overnight. Walnuts every day — your daily LDL-lowering dose. Non-negotiable.', p: 5, f: 2, c: 3, k: 110, tags: ['cooling'] },
    { name: 'Warm water + soaked peanuts (20g) + walnuts (4)', detail: 'Soak peanuts overnight like almonds — removes the heating quality. Good protein start.', p: 6, f: 2, c: 5, k: 120, tags: ['summer', 'cooling'] },
    { name: 'Warm water + soaked flaxseed (1 tsp) + almonds (8)', detail: '1 tsp flaxseeds soaked overnight forms a cooling mucilaginous gel. Drink water + seeds. Great gut starter in summer.', p: 4, f: 3, c: 3, k: 95, tags: ['summer', 'cooling', 'fibre'] },
    { name: 'Saunf water + soaked almonds (8) + walnuts (4)', detail: '1 tsp fennel seeds soaked in 1L water overnight. Drink a glass first thing. Cooling, reduces bloating — ideal at 40°C.', p: 5, f: 2, c: 4, k: 105, tags: ['summer', 'cooling'] },
  ],
  bfast: [
    { name: 'Overnight oats — hung curd + chia + half banana', detail: '50g oats + 100g hung curd + 1 tbsp chia + half banana. Prep night before. Hung curd doubles protein vs milk.', p: 19, f: 8, c: 38, k: 320, tags: ['oats', 'fibre', 'cooling', 'quick'] },
    { name: 'Overnight oats — hung curd + chia + pomegranate', detail: 'Same base, pomegranate topping. Lower sugar than banana. Antioxidants help LDL oxidation.', p: 19, f: 8, c: 36, k: 315, tags: ['oats', 'fibre', 'cooling', 'quick'] },
    { name: 'Overnight oats — hung curd + chia + mixed berries', detail: 'Same base, berries on top. Lowest sugar version. Weekend feel without extra effort.', p: 19, f: 9, c: 34, k: 310, tags: ['oats', 'fibre', 'cooling', 'quick'] },
    { name: 'Sattu stuffed paratha ×2 + hung curd (50g)', detail: 'Sattu + onion + ajwain + chilli stuffing. 1 tsp mustard oil only. 1 tbsp flaxseed in atta. Better at dinner in peak summer.', p: 18, f: 6, c: 48, k: 340, tags: ['sattu'] },
    { name: 'Moong dal chilla ×2 + hung curd (50g) as dip', detail: '1 tbsp flaxseed in batter. Hung curd as dip instead of chutney. Light, quick, high protein.', p: 17, f: 6, c: 42, k: 305, tags: ['quick', 'fibre'] },
    { name: 'Moong dal chilla ×3 (plain + mint chutney)', detail: '3 chillas with mint chutney. Higher carb but very filling. Good on high-activity days.', p: 18, f: 5, c: 58, k: 335, tags: ['quick'] },
    { name: 'Besan chilla ×2 + moong sprouts (half cup)', detail: 'Gram flour chilla, slightly more protein than wheat. Sprouts on the side with lemon. Light and summery.', p: 15, f: 5, c: 44, k: 300, tags: ['summer', 'quick'] },
    { name: 'Moong sprouts chaat + 1 whole wheat roti', detail: 'Boiled sprouts + onion + tomato + chaat masala + lemon. Sunday-feel breakfast. Roti alongside.', p: 13, f: 5, c: 38, k: 280, tags: ['summer', 'cooling', 'fibre'] },
    { name: 'Sattu sherbet + moong chilla ×2', detail: 'Lighter summer morning combo. Sattu sherbet as the drink, 2 chillas as the food. Total protein still strong.', p: 18, f: 5, c: 60, k: 330, tags: ['sattu', 'summer', 'cooling'] },
  ],
  midmorn: [
    { name: 'Sattu sherbet (4 tbsp in cold water + lemon + jeera)', detail: 'The best summer mid-morning drink. Low GI, 11g protein, cooling. Use chilled water or ice cubes.', p: 11, f: 4, c: 23, k: 145, tags: ['sattu', 'summer', 'cooling', 'quick'] },
    { name: 'Hung curd (100g) + 1 apple', detail: 'Daily anchor. Apple adds pectin — soluble fibre that feeds gut bacteria.', p: 10, f: 3, c: 10, k: 130, tags: ['quick', 'cooling'] },
    { name: 'Hung curd (100g) + 1 guava', detail: 'Guava has the highest fibre of any common fruit — 5g. Best fibre-per-calorie fruit.', p: 10, f: 6, c: 13, k: 130, tags: ['fibre', 'cooling', 'quick'] },
    { name: 'Hung curd (100g) + 1 pear', detail: 'Pear is cooling and high fibre. Good summer choice.', p: 10, f: 5, c: 11, k: 130, tags: ['cooling', 'quick'] },
    { name: 'Hung curd (100g) + watermelon (1 cup)', detail: 'Most cooling mid-morning option in summer. Watermelon is 92% water — excellent for hydration.', p: 10, f: 2, c: 15, k: 130, tags: ['summer', 'cooling', 'quick'] },
    { name: 'Coconut water + soaked almonds (6)', detail: 'Replace mid-morning snack with coconut water in peak summer. Best natural electrolyte.', p: 4, f: 2, c: 18, k: 140, tags: ['summer', 'cooling'] },
    { name: 'Aam panna (unsweetened) + hung curd (50g)', detail: 'Raw mango + jeera + black salt + mint. Traditional heat stroke prevention. Hung curd for protein.', p: 6, f: 2, c: 20, k: 140, tags: ['summer', 'cooling'] },
    { name: 'Nimbu pani (unsweetened) + roasted chana (20g)', detail: 'Lemon + water + black salt + jeera + mint. Chana for protein. Budget and summer perfect.', p: 5, f: 3, c: 16, k: 130, tags: ['summer', 'cooling', 'quick'] },
  ],
  lunch: [
    { name: 'Masoor dal + seasonal sabzi + 2 roti + kachumber', detail: 'Masoor dal (1 katori). Kachumber salad eaten first. 1 tbsp flaxseed in atta. Rotate sabzi daily.', p: 15, f: 7, c: 52, k: 420, tags: ['fibre', 'quick'] },
    { name: 'Moong dal + palak sabzi + 2 roti + kachumber', detail: 'Moong is the best summer dal — light, cooling, easy to digest. Palak adds iron and fibre.', p: 15, f: 8, c: 50, k: 415, tags: ['fibre', 'summer', 'cooling'] },
    { name: 'Chana dal + bhindi sabzi + 2 roti + kachumber', detail: 'Chana dal has highest protein of all dals. Bhindi is high soluble fibre. Good LDL-lowering lunch.', p: 15, f: 8, c: 50, k: 415, tags: ['fibre'] },
    { name: 'Tur dal + lauki sabzi + 2 roti + kachumber', detail: 'Tur dal is cooling in summer. Lauki (bottle gourd) is 90% water — best summer sabzi.', p: 14, f: 7, c: 50, k: 400, tags: ['summer', 'cooling', 'fibre'] },
    { name: 'Rajma + 2 roti + kachumber + curd', detail: 'High protein, high fibre. Good for LDL. Slightly heavy for summer — have on cooler days or in AC.', p: 16, f: 9, c: 54, k: 440, tags: ['fibre'] },
    { name: 'Chole + 2 roti + kachumber', detail: 'Simple home chole, no frying, amchur for sourness. High protein and fibre. Sunday special or any day.', p: 14, f: 8, c: 52, k: 430, tags: ['fibre'] },
    { name: 'Low-fat paneer matar curry + dal + 2 roti + kachumber', detail: 'Paneer (75g) + dal alongside. Low-fat only, no cream. Max 2× per week.', p: 22, f: 7, c: 52, k: 460, tags: ['paneer', 'fibre'] },
    { name: 'Soya chunk pulao + raita + kachumber', detail: '30g dry soya + 40g rice + veg + raita. Check no soya yesterday or tomorrow.', p: 22, f: 5, c: 38, k: 390, tags: ['soya', 'fibre'] },
    { name: 'Moong dal khichdi + curd + kachumber', detail: 'Most cooling, easiest to digest. Good for very hot days or when appetite is low.', p: 14, f: 5, c: 48, k: 380, tags: ['summer', 'cooling', 'quick'] },
    { name: 'Lobiya curry + 2 roti + kachumber', detail: 'Black-eyed peas, high protein and fibre. Simple tomato gravy. Slightly cooling.', p: 14, f: 7, c: 50, k: 405, tags: ['fibre'] },
  ],
  snack: [
    { name: 'Ragi chaas (1 tsp ragi + dahi + water + jeera)', detail: 'Cooling, high calcium. Chaas day. Alternate with chana chaat strictly.', p: 4, f: 2, c: 8, k: 65, tags: ['chaas', 'summer', 'cooling', 'quick'] },
    { name: 'Sattu chaas (1 tbsp sattu + chaas + jeera + black salt)', detail: 'Chaas upgraded with sattu. Extra protein and fibre. Good on non-sattu-morning days.', p: 6, f: 3, c: 10, k: 80, tags: ['chaas', 'sattu', 'summer', 'cooling', 'quick'] },
    { name: 'Plain chaas with pudina + jeera + black salt', detail: 'Simplest version. Add fresh mint for extra cooling. Use when snack slot has protein from chaat alongside.', p: 3, f: 1, c: 4, k: 45, tags: ['chaas', 'summer', 'cooling', 'quick'] },
    { name: 'Roasted chana chaat — classic (30g + onion + tomato + chaat masala)', detail: 'Chana day. Classic, 3 minutes to make. Alternate strictly with chaas.', p: 7, f: 5, c: 18, k: 130, tags: ['chana', 'fibre', 'quick'] },
    { name: 'Roasted chana chaat — cucumber version (30g + cucumber + black salt + lemon)', detail: 'Best summer version. Cucumber adds hydration and volume.', p: 7, f: 6, c: 19, k: 135, tags: ['chana', 'summer', 'cooling', 'fibre', 'quick'] },
    { name: 'Roasted chana chaat — sprouts version (20g chana + 2 tbsp moong sprouts)', detail: 'Higher protein. Good on non-soya days when dinner is lighter.', p: 8, f: 6, c: 20, k: 145, tags: ['chana', 'fibre'] },
    { name: 'Soya tikki ×2 (tawa) + plain chaas', detail: '25g dry soya minced + small potato + onion + besan. Tawa cooked. Soya day — check constraint.', p: 17, f: 4, c: 22, k: 215, tags: ['soya', 'chaas'] },
    { name: 'Peanut butter (1 tbsp natural) on 1 thin roti + chaas', detail: 'Natural peanut butter only — no added sugar. Filling, macro-friendly.', p: 9, f: 3, c: 20, k: 195, tags: ['quick'] },
    { name: 'Nimbu pani + roasted chana (small fistful)', detail: 'Summer combo. Cooling drink + crunchy protein snack. Good on very hot afternoons.', p: 5, f: 3, c: 16, k: 120, tags: ['summer', 'cooling', 'quick'] },
    { name: 'Coconut water + soaked peanuts (15g)', detail: 'Best summer electrolyte + protein combo. Use on peak heat days (42°C+).', p: 5, f: 2, c: 18, k: 135, tags: ['summer', 'cooling'] },
    { name: 'Hung curd (100g) + cucumber slices', detail: 'Near-zero carb snack. Protein + probiotics. Good when lunch was heavy.', p: 10, f: 2, c: 7, k: 115, tags: ['cooling', 'quick'] },
  ],
  dinner: [
    { name: 'Soya chunk pulao (30g dry soya + 35g rice + veg)', detail: 'Boil soya, squeeze dry, cook with whole spices + veg + rice. Full family meal. Soya day — check constraint.', p: 21, f: 4, c: 30, k: 360, tags: ['soya'] },
    { name: 'Soya chunk sabzi + 1 jowar roti', detail: 'Dry soya sabzi with onion, tomato, capsicum. Different texture from pulao. Soya day.', p: 20, f: 4, c: 26, k: 325, tags: ['soya'] },
    { name: 'Soya tikki ×2 + dal soup + 1 roti', detail: 'Tikki as main + thin dal as soup alongside. Soya day — check constraint.', p: 19, f: 4, c: 28, k: 330, tags: ['soya'] },
    { name: 'Low-fat paneer bhurji (75g) + 1 roti', detail: 'Scrambled with onion, tomato, capsicum. No cream. Paneer day — max 2×/week.', p: 17, f: 2, c: 20, k: 310, tags: ['paneer'] },
    { name: 'Low-fat paneer curry (75g) + 1 jowar roti + thin dal', detail: 'Matar or kadhai paneer, low-fat only. Thin dal as soup. Paneer day.', p: 18, f: 4, c: 24, k: 330, tags: ['paneer'] },
    { name: 'Sattu paratha ×2 (shallow) + hung curd', detail: 'Sattu + onion + ajwain + chilli. 1 tsp oil. Best at dinner in summer when temp drops.', p: 18, f: 6, c: 48, k: 340, tags: ['sattu'] },
    { name: 'Moong dal khichdi (light ghee) + curd', detail: 'Most cooling, easiest to digest. Best on hot days or when feeling heavy. 1 tsp ghee only.', p: 13, f: 5, c: 42, k: 340, tags: ['summer', 'cooling', 'quick'] },
    { name: 'Lobiya curry (light) + 1 jowar roti', detail: 'Black-eyed peas in tomato gravy. High protein, high fibre. Cooling. Light dinner.', p: 12, f: 6, c: 28, k: 290, tags: ['fibre', 'cooling'] },
    { name: 'Chole (light) + 1 roti', detail: 'Simple home chole, minimal oil. Good when lunch was dal-based for variety.', p: 13, f: 7, c: 38, k: 360, tags: ['fibre'] },
    { name: 'Moong dal + seasonal sabzi + 1 roti', detail: 'Lightest standard dinner. Good on days when lunch was heavy or eaten late.', p: 13, f: 5, c: 32, k: 310, tags: ['summer', 'cooling', 'quick'] },
    { name: 'Broccoli paneer pasta (whole wheat / chickpea)', detail: '65g pasta + 60g low-fat paneer + broccoli sauce (hung curd base, no cream). Paneer day. Reduce lunch roti to 1 on pasta days.', p: 28, f: 10, c: 42, k: 480, tags: ['paneer', 'flexi', 'fibre'] },
    { name: 'Roasted capsicum paneer pasta (whole wheat / chickpea)', detail: '65g pasta + 60g low-fat paneer + charred capsicum sauce (hung curd base). Paneer day. Reduce lunch roti on pasta days.', p: 26, f: 8, c: 45, k: 490, tags: ['paneer', 'flexi'] },
    { name: 'Clear vegetable soup + 1 roti', detail: 'Lightest possible dinner. Good after a heavy paneer lunch. Seasonal veg, minimal oil.', p: 5, f: 3, c: 18, k: 155, tags: ['summer', 'cooling', 'quick'] },
  ],
};
